server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:h2:mem:traveldb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  h2:
    console:
      enabled: false

weather:
  api:
    base-url: https://api.openweathermap.org/data/2.5
    api-key: ${WEATHER_API_KEY:YOUR_CORRECT_API_KEY_HERE}

logging:
  level:
    com.homedepot.travel: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
