server:
  port: 8081

spring:
  application:
    name: travel-packing-assistant
  datasource:
    url: jdbc:h2:mem:traveldb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

# Weather API configuration
weather:
  api:
    base-url: https://api.openweathermap.org/data/2.5
    api-key: ${WEATHER_API_KEY:e49958eec2334c0aee1692d1c8042ae5}
    timeout: 5000

# Travel configuration
travel:
  max-days: 14
  max-locations-per-day: 3

logging:
  level:
    com.homedepot.travel: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
